### ISSUE TITLE
Sponsors section

### ISSUE THREAD

**Issue by bosschaert** [adobe-basel/summit-emea#11]
Reference site: https://summit-emea.adobe.com/emea/
The links in the navbar can go to the original site.

Current:
<img width="593" alt="Screenshot 2023-05-04 at 14 26 19" src="https://user-images.githubusercontent.com/226514/236218565-32b2a416-bcad-4c49-b6da-9d105b741e85.png">

Expected:
<img width="1216" alt="Screenshot 2023-05-04 at 14 24 25" src="https://user-images.githubusercontent.com/226514/236218353-cbd67797-553d-4c45-b166-c19b57f18016.png">

**Comment by sumitshinde-84** [comment]
Hi @bosschaert, I hope this message finds you well. My name is Sumit Shinde and I'm writing to express my interest in a frontend development internship position. I came across your profile and was impressed with your experience and skills in this field. I was wondering if you might be able to offer any advice or guidance on finding such an opportunity. I would greatly appreciate any help or direction you could provide. Thank you for your time and consideration.
